# -*- coding: utf-8 -*-
"""Capstoneproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uPORZtmMmm7N3vQbdjwCtjUmSrllEmV
"""

pip install fastapi uvicorn sqlalchemy pydantic

from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

DATABASE_URL = "sqlite:///./todo.db"

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False}
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

Base = declarative_base()

from sqlalchemy import Column, Integer, String, Boolean

class TaskDB(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    is_done = Column(Boolean, default=False)

from pydantic import BaseModel


class Task(BaseModel):
    id: int
    title: str
    is_done: bool = False


class TaskCreate(BaseModel):
    title: str
    is_done: bool = False


class TaskUpdate(BaseModel):
    title: str | None = None
    is_done: bool | None = None

!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session

app = FastAPI()

Base.metadata.create_all(bind=engine)


def get_db():
    db = SessionLocal()

    try:
        yield db
    finally:
        db.close()


@app.get("/")
def home():
    return {"message": "Task Management API is running"}


# CREATE
@app.post("/tasks")
def create_task(task: TaskCreate, db: Session = Depends(get_db)):

    new_task = TaskDB(
        title=task.title,
        is_done=task.is_done
    )

    db.add(new_task)
    db.commit()
    db.refresh(new_task)

    return new_task


# READ ALL
@app.get("/tasks")
def get_tasks(db: Session = Depends(get_db)):

    tasks = db.query(TaskDB).all()

    return tasks


# READ ONE
@app.get("/tasks/{task_id}")
def get_task(task_id: int, db: Session = Depends(get_db)):

    task = db.query(TaskDB).filter(
        TaskDB.id == task_id
    ).first()

    if task is None:
        raise HTTPException(
            status_code=404,
            detail="Task not found"
        )

    return task


# UPDATE
@app.put("/tasks/{task_id}")
def update_task(
    task_id: int,
    task_data: TaskUpdate,
    db: Session = Depends(get_db)
):

    task = db.query(TaskDB).filter(
        TaskDB.id == task_id
    ).first()

    if task is None:
        raise HTTPException(
            status_code=404,
            detail="Task not found"
        )

    if task_data.title is not None:
        task.title = task_data.title

    if task_data.is_done is not None:
        task.is_done = task_data.is_done

    db.commit()
    db.refresh(task)

    return task


# DELETE
@app.delete("/tasks/{task_id}")
def delete_task(
    task_id: int,
    db: Session = Depends(get_db)
):

    task = db.query(TaskDB).filter(
        TaskDB.id == task_id
    ).first()

    if task is None:
        raise HTTPException(
            status_code=404,
            detail="Task not found"
        )

    db.delete(task)
    db.commit()

    return {
        "message": "Task deleted successfully"
    }

!pip install matplotlib-venn

from pyngrok import ngrok
import subprocess
import time

process = subprocess.Popen(
    ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
)

time.sleep(3)

public_url = ngrok.connect(8000)

print("Your API URL:")
print(public_url)